# modul halaman conclusion
import streamlit as st

def conclusion():
    st.write("## Conclusion")
    st.write("""
    **Insight:**
    - Berdasarkan analisis yang dilakukan, cuaca cerah ternyata menjadi faktor utama yang mendorong tingginya jumlah penyewaan sepeda, di mana pada kondisi ini jumlah penyewaan mencapai angka tertinggi dibandingkan kondisi cuaca lainnya. Setelah cuaca cerah, cuaca berawan menduduki posisi kedua dalam jumlah penyewaan sepeda, diikuti oleh cuaca dengan hujan ringan, dan yang paling sedikit adalah ketika cuaca badai.

    - Jika dilihat dari segi musim, musim gugur tampak mendominasi dalam hal jumlah penyewaan sepeda. Pada musim ini, penyewaan sepeda berada pada puncaknya, jauh lebih tinggi dibandingkan dengan musim-musim lainnya. Setelah musim gugur, musim panas menyusul dengan jumlah penyewaan yang cukup tinggi, diikuti oleh musim dingin, dan akhirnya musim semi yang mencatat jumlah penyewaan paling rendah.

    - Dari analisis terhadap hari dalam seminggu, diketahui bahwa hari Jumat adalah hari yang mencatatkan jumlah penyewaan sepeda tertinggi. Setelah Jumat, hari Kamis dan Sabtu menyusul sebagai hari-hari dengan jumlah penyewaan yang juga tinggi, sedangkan hari Rabu, Selasa, dan Senin berada di posisi selanjutnya. Menariknya, hari Minggu mencatat jumlah penyewaan sepeda paling sedikit, meskipun secara umum akhir pekan sering dianggap sebagai waktu favorit untuk aktivitas luar ruangan.

    - Selain faktor hari dan musim, waktu juga memainkan peran penting dalam tren penyewaan sepeda. Jam 17.00 hingga 18.00 (sore hari) merupakan waktu di mana jumlah penyewaan sepeda mencapai puncaknya, yang mungkin disebabkan oleh banyaknya orang yang pulang kerja pada jam-jam tersebut. Di urutan kedua, jam 08.00 (pagi hari) menunjukkan lonjakan penyewaan, kemungkinan besar karena banyak orang memulai aktivitas harian mereka. Sebaliknya, jam 04.00 dini hari menunjukkan tingkat penyewaan paling rendah, di mana mayoritas orang belum aktif beraktivitas pada waktu tersebut.

    - Analisis data juga mengungkap adanya 10 anomali yang signifikan terkait penyewaan sepeda. Sebagai contoh, pada tanggal 15 September 2012, terjadi lonjakan penyewaan sepeda yang signifikan, yang dikaitkan dengan acara tahunan 'H Street Festival', sebuah event jalanan besar yang menarik banyak pengunjung di Washington, D.C. Namun, di sisi lain, terdapat penurunan drastis pada tanggal 29 Oktober 2012 yang bertepatan dengan terjadinya "Hurricane Sandy", salah satu badai besar yang memaksa banyak orang untuk membatasi aktivitas luar ruangan. Selain itu, masih terdapat beberapa insiden lain yang mempengaruhi pola penyewaan pada tanggal-tanggal tertentu.

    - Selama periode dua tahun dari 2011 hingga 2012, tren penyewaan sepeda secara keseluruhan menunjukkan peningkatan yang konsisten, khususnya jika dilihat dari akumulasi bulanan. Namun, yang menarik adalah adanya penurunan signifikan yang terjadi setiap bulan Oktober di kedua tahun tersebut, yang kemungkinan besar disebabkan oleh faktor-faktor eksternal seperti cuaca atau event tertentu.

    - Analisis lebih lanjut terhadap korelasi dan koefisien regresi menunjukkan bahwa suhu memiliki peran yang sangat signifikan dalam mempengaruhi jumlah penyewaan sepeda. Suhu yang lebih hangat cenderung meningkatkan jumlah penyewaan. Di sisi lain, meskipun kelembaban udara dan kecepatan angin juga memiliki pengaruh, pengaruh kedua faktor ini jauh lebih kecil jika dibandingkan dengan suhu. Dapat dilihat juga pembuktian pengaruh suhu pada visualisasi scatterplot ini menunjukkan hubungan antara suhu (temperature) dan jumlah penyewaan sepeda (count of rentals), dengan data dibagi menjadi tiga cluster: cluster 0 (ungu) yang mendominasi pada suhu rendah dengan jumlah penyewaan lebih sedikit, cluster 1 (hijau) yang mencerminkan penyewaan lebih bervariasi pada suhu menengah, dan cluster 2 (kuning) yang menunjukkan penyewaan tertinggi pada suhu hangat hingga panas. Semakin tinggi suhu, semakin meningkat pula jumlah penyewaan sepeda, yang terlihat dari dominasi cluster kuning pada suhu di atas 0.6. Dengan kata lain, suhu hangat berperan sebagai faktor signifikan yang mendorong permintaan penyewaan sepeda, sedangkan pada suhu yang lebih rendah jumlah penyewaan cenderung lebih sedikit. Anomali atau outliers yang terdeteksi pada grafik juga menunjukkan adanya beberapa penyewaan yang tidak mengikuti pola umum, mungkin disebabkan oleh faktor-faktor eksternal seperti acara khusus atau cuaca ekstrem.
    """)
